name: NodeJS with Webpack

on:
  schedule:
  - cron: "10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: e2e Tests
        uses: cypress-io/github-action@v2
        with:
          node-version: 16

      - name: Build
        run: |
         node_modules/.bin/cypress install,
         npm install,
         npm run start
