name: NodeJS with Webpack

on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --prefix Bari-Autom

      - name: Run Cypress tests
        run: npm cypress run --project ./Bari-Autom
