name: NodeJS with Webpack

on:
  schedule:
  - cron: "10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start

      - name: Build
        run: |
         npm install,
         node_modules/.bin/cypress install
         npm run start
